version: '3'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: appsecret
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://appuser:appsecret@db:5432/appdb
      REDIS_URL: redis://redis:6379
      TRANSLATE_PROVIDER: google
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    depends_on:
      - db
      - redis
    ports:
      - "5000:5000"
  frontend:
    build: ./client
    environment:
      REACT_APP_API_URL: http://backend:5000
    depends_on:
      - backend
    ports:
      - "3000:3000"
volumes:
  dbdata:
